import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:go_router/go_router.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';
import 'dart:convert';
import 'package:flutter/foundation.dart' show kIsWeb;
import '../../../core/theme/app_theme.dart';
import '../../../core/services/auth_service.dart';

/// Contract Screen - Generate, download, share, edit, print contracts
class ContractScreen extends StatefulWidget {
  final String assessmentId;

  const ContractScreen({
    super.key,
    required this.assessmentId,
  });

  @override
  State<ContractScreen> createState() => _ContractScreenState();
}

class _ContractScreenState extends State<ContractScreen> {
  bool _isLoading = true;
  bool _isGenerating = false;
  String? _error;
  Map<String, dynamic>? _preview;
  List<Map<String, dynamic>> _templates = [];
  String _selectedTemplate = 'property';
  bool _contractGenerated = false;
  String? _downloadUrl;

  // Editable fields
  late TextEditingController _insuredNameController;
  late TextEditingController _premiumController;
  late TextEditingController _deductibleController;
  late TextEditingController _sumInsuredController;
  late TextEditingController _territoryController;

  @override
  void initState() {
    super.initState();
    _insuredNameController = TextEditingController();
    _premiumController = TextEditingController();
    _deductibleController = TextEditingController();
    _sumInsuredController = TextEditingController();
    _territoryController = TextEditingController();
    _checkAuthAndLoad();
  }

  @override
  void dispose() {
    _insuredNameController.dispose();
    _premiumController.dispose();
    _deductibleController.dispose();
    _sumInsuredController.dispose();
    _territoryController.dispose();
    super.dispose();
  }

  Future<void> _checkAuthAndLoad() async {
    if (!authService.isLoggedIn) {
      if (mounted) {
        context.go('/login');
      }
      return;
    }
    _loadData();
  }

  Future<void> _loadData() async {
    setState(() {
      _isLoading = true;
      _error = null;
    });

    try {
      // Fetch templates
      final templatesResponse = await authService.get('/contracts/templates');

      if (templatesResponse.statusCode == 200) {
        final data = jsonDecode(templatesResponse.body);
        setState(() {
          _templates = List<Map<String, dynamic>>.from(data['templates'] ?? []);
        });
      } else if (templatesResponse.statusCode == 401) {
        if (mounted) {
          context.go('/login');
        }
        return;
      }

      // Fetch preview data
      final previewResponse = await authService.get('/contracts/${widget.assessmentId}/preview');

      if (previewResponse.statusCode == 200) {
        final data = jsonDecode(previewResponse.body);
        setState(() {
          _preview = data;
          _insuredNameController.text = data['insured_name'] ?? '';
          _premiumController.text = (data['premium'] ?? 0).toString();
          _deductibleController.text = (data['deductible'] ?? 0).toString();
          _sumInsuredController.text = (data['sum_insured'] ?? 0).toString();
          _territoryController.text = data['territory'] ?? '';
          _isLoading = false;
        });
      } else if (previewResponse.statusCode == 401) {
        if (mounted) {
          context.go('/login');
        }
      } else {
        setState(() {
          _error = 'Failed to load contract data';
          _isLoading = false;
        });
      }
    } catch (e) {
      setState(() {
        _error = 'Error: $e';
        _isLoading = false;
      });
    }
  }

  Future<void> _generateContract() async {
    setState(() => _isGenerating = true);

    try {
      final url = '/api/v1/contracts/generate/${widget.assessmentId}?template_id=$_selectedTemplate';
      setState(() {
        _downloadUrl = url;
        _contractGenerated = true;
        _isGenerating = false;
      });
    } catch (e) {
      setState(() {
        _error = 'Generation failed: $e';
        _isGenerating = false;
      });
    }
  }

  void _downloadPdf() {
    if (_downloadUrl == null) return;
    launchUrl(Uri.parse(_downloadUrl!), mode: LaunchMode.externalApplication);
  }

  void _sharePdf() {
    if (_downloadUrl == null) return;

    final shareText = '''
Insurance Contract Ready for Download

Policy: ${_preview?['reference_number'] ?? 'N/A'}
Insured: ${_insuredNameController.text}
Premium: €${_premiumController.text}

Download: $_downloadUrl

Generated by InstantRisk
''';

    Share.share(shareText);
  }

  void _showQrCode() {
    if (_downloadUrl == null) return;

    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Share Contract'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              width: 200,
              height: 200,
              decoration: BoxDecoration(
                border: Border.all(color: AppTheme.border),
                borderRadius: BorderRadius.circular(8),
              ),
              child: Center(
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Icon(Icons.qr_code_2, size: 100, color: AppTheme.primaryDark),
                    const SizedBox(height: 8),
                    Text(
                      'QR Code',
                      style: TextStyle(color: AppTheme.textHint, fontSize: 12),
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 16),
            const Text(
              'Scan to download contract',
              style: TextStyle(color: AppTheme.textSecondary),
            ),
            const SizedBox(height: 16),
            Row(
              children: [
                Expanded(
                  child: Text(
                    _downloadUrl!,
                    style: const TextStyle(fontSize: 10, color: AppTheme.textHint),
                    maxLines: 2,
                    overflow: TextOverflow.ellipsis,
                  ),
                ),
                IconButton(
                  icon: const Icon(Icons.copy, size: 20),
                  onPressed: () {
                    Clipboard.setData(ClipboardData(text: _downloadUrl!));
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(content: Text('Link copied!')),
                    );
                  },
                ),
              ],
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Close'),
          ),
        ],
      ),
    );
  }

  void _printPdf() {
    if (_downloadUrl == null) return;
    launchUrl(Uri.parse(_downloadUrl!), mode: LaunchMode.externalApplication);
    if (kIsWeb) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('PDF opened - use browser print (Ctrl+P)')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.background,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios, color: AppTheme.textPrimary),
          onPressed: () => context.go('/reports/results/${widget.assessmentId}'),
        ),
        title: const Text(
          'Generate Contract',
          style: TextStyle(
            fontSize: 18,
            fontWeight: FontWeight.w600,
            color: AppTheme.textPrimary,
            fontFamily: 'Inter',
          ),
        ),
        centerTitle: true,
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : _error != null
              ? Center(
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      Icon(Icons.error_outline, size: 64, color: AppTheme.danger),
                      const SizedBox(height: 16),
                      Text(_error!, style: TextStyle(color: AppTheme.textSecondary)),
                      const SizedBox(height: 16),
                      ElevatedButton(onPressed: _loadData, child: const Text('Retry')),
                    ],
                  ),
                )
              : SingleChildScrollView(
                  padding: const EdgeInsets.all(20),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      // Template Selection
                      const Text(
                        'Select Template',
                        style: TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w600,
                          color: AppTheme.textPrimary,
                        ),
                      ),
                      const SizedBox(height: 12),
                      SizedBox(
                        height: 120,
                        child: ListView.builder(
                          scrollDirection: Axis.horizontal,
                          itemCount: _templates.length,
                          itemBuilder: (context, index) {
                            final template = _templates[index];
                            final isSelected = template['id'] == _selectedTemplate;
                            return GestureDetector(
                              onTap: () => setState(() => _selectedTemplate = template['id']),
                              child: Container(
                                width: 150,
                                margin: const EdgeInsets.only(right: 12),
                                padding: const EdgeInsets.all(12),
                                decoration: BoxDecoration(
                                  color: isSelected ? AppTheme.primaryDark.withOpacity(0.1) : AppTheme.surface,
                                  borderRadius: BorderRadius.circular(12),
                                  border: Border.all(
                                    color: isSelected ? AppTheme.primaryDark : AppTheme.border,
                                    width: isSelected ? 2 : 1,
                                  ),
                                ),
                                child: Column(
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Icon(
                                      _getTemplateIcon(template['id']),
                                      color: isSelected ? AppTheme.primaryDark : AppTheme.textHint,
                                    ),
                                    const SizedBox(height: 8),
                                    Text(
                                      template['name'] ?? 'Template',
                                      style: TextStyle(
                                        fontSize: 12,
                                        fontWeight: FontWeight.w600,
                                        color: isSelected ? AppTheme.primaryDark : AppTheme.textPrimary,
                                      ),
                                      maxLines: 2,
                                      overflow: TextOverflow.ellipsis,
                                    ),
                                  ],
                                ),
                              ),
                            );
                          },
                        ),
                      ),
                      const SizedBox(height: 24),

                      // Editable Fields
                      const Text(
                        'Policy Details (Editable)',
                        style: TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w600,
                          color: AppTheme.textPrimary,
                        ),
                      ),
                      const SizedBox(height: 12),

                      _buildEditableField('Insured Name', _insuredNameController, Icons.business),
                      _buildEditableField('Premium (€)', _premiumController, Icons.euro, isNumber: true),
                      _buildEditableField('Deductible (€)', _deductibleController, Icons.remove_circle_outline, isNumber: true),
                      _buildEditableField('Sum Insured (€)', _sumInsuredController, Icons.account_balance, isNumber: true),
                      _buildEditableField('Territory', _territoryController, Icons.location_on),

                      const SizedBox(height: 24),

                      // Reference Info
                      Container(
                        padding: const EdgeInsets.all(16),
                        decoration: BoxDecoration(
                          color: AppTheme.surface,
                          borderRadius: BorderRadius.circular(12),
                          border: Border.all(color: AppTheme.border),
                        ),
                        child: Column(
                          children: [
                            _buildInfoRow('Reference', _preview?['reference_number'] ?? 'N/A'),
                            _buildInfoRow('Risk Category', _preview?['risk_category'] ?? 'N/A'),
                            _buildInfoRow('Effective Date', _formatDate(_preview?['effective_date'])),
                            _buildInfoRow('Expiry Date', _formatDate(_preview?['expiry_date'])),
                          ],
                        ),
                      ),
                      const SizedBox(height: 24),

                      // Generate Button
                      if (!_contractGenerated)
                        SizedBox(
                          width: double.infinity,
                          child: ElevatedButton(
                            onPressed: _isGenerating ? null : _generateContract,
                            style: ElevatedButton.styleFrom(
                              backgroundColor: AppTheme.primaryDark,
                              padding: const EdgeInsets.symmetric(vertical: 16),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                            child: _isGenerating
                                ? const SizedBox(
                                    height: 20,
                                    width: 20,
                                    child: CircularProgressIndicator(
                                      strokeWidth: 2,
                                      valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                                    ),
                                  )
                                : const Text(
                                    'Generate Contract',
                                    style: TextStyle(
                                      fontSize: 16,
                                      fontWeight: FontWeight.w600,
                                    ),
                                  ),
                          ),
                        ),

                      // Action Buttons (after generation)
                      if (_contractGenerated) ...[
                        Container(
                          padding: const EdgeInsets.all(16),
                          decoration: BoxDecoration(
                            color: AppTheme.success.withOpacity(0.1),
                            borderRadius: BorderRadius.circular(12),
                            border: Border.all(color: AppTheme.success),
                          ),
                          child: Row(
                            children: [
                              Icon(Icons.check_circle, color: AppTheme.success),
                              const SizedBox(width: 12),
                              const Expanded(
                                child: Text(
                                  'Contract generated successfully!',
                                  style: TextStyle(
                                    color: AppTheme.success,
                                    fontWeight: FontWeight.w600,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(height: 20),

                        // Download Button
                        SizedBox(
                          width: double.infinity,
                          child: ElevatedButton.icon(
                            onPressed: _downloadPdf,
                            icon: const Icon(Icons.download),
                            label: const Text('Download PDF'),
                            style: ElevatedButton.styleFrom(
                              backgroundColor: AppTheme.primaryDark,
                              padding: const EdgeInsets.symmetric(vertical: 14),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(12),
                              ),
                            ),
                          ),
                        ),
                        const SizedBox(height: 12),

                        // Share & QR Row
                        Row(
                          children: [
                            Expanded(
                              child: OutlinedButton.icon(
                                onPressed: _sharePdf,
                                icon: const Icon(Icons.share),
                                label: const Text('Share'),
                                style: OutlinedButton.styleFrom(
                                  padding: const EdgeInsets.symmetric(vertical: 14),
                                  side: const BorderSide(color: AppTheme.border),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(12),
                                  ),
                                ),
                              ),
                            ),
                            const SizedBox(width: 12),
                            Expanded(
                              child: OutlinedButton.icon(
                                onPressed: _showQrCode,
                                icon: const Icon(Icons.qr_code),
                                label: const Text('QR Code'),
                                style: OutlinedButton.styleFrom(
                                  padding: const EdgeInsets.symmetric(vertical: 14),
                                  side: const BorderSide(color: AppTheme.border),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(12),
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 12),

                        // Print & Regenerate Row
                        Row(
                          children: [
                            Expanded(
                              child: OutlinedButton.icon(
                                onPressed: _printPdf,
                                icon: const Icon(Icons.print),
                                label: const Text('Print'),
                                style: OutlinedButton.styleFrom(
                                  padding: const EdgeInsets.symmetric(vertical: 14),
                                  side: const BorderSide(color: AppTheme.border),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(12),
                                  ),
                                ),
                              ),
                            ),
                            const SizedBox(width: 12),
                            Expanded(
                              child: OutlinedButton.icon(
                                onPressed: () {
                                  setState(() => _contractGenerated = false);
                                },
                                icon: const Icon(Icons.edit),
                                label: const Text('Edit'),
                                style: OutlinedButton.styleFrom(
                                  padding: const EdgeInsets.symmetric(vertical: 14),
                                  side: const BorderSide(color: AppTheme.border),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(12),
                                  ),
                                ),
                              ),
                            ),
                          ],
                        ),
                      ],
                      const SizedBox(height: 40),
                    ],
                  ),
                ),
    );
  }

  Widget _buildEditableField(String label, TextEditingController controller, IconData icon, {bool isNumber = false}) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 12),
      child: TextField(
        controller: controller,
        keyboardType: isNumber ? TextInputType.number : TextInputType.text,
        decoration: InputDecoration(
          labelText: label,
          prefixIcon: Icon(icon, color: AppTheme.textHint),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: AppTheme.border),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: AppTheme.border),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: AppTheme.primaryDark),
          ),
          filled: true,
          fillColor: AppTheme.surface,
        ),
      ),
    );
  }

  Widget _buildInfoRow(String label, String value) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: TextStyle(color: AppTheme.textHint)),
          Text(value, style: const TextStyle(fontWeight: FontWeight.w600)),
        ],
      ),
    );
  }

  IconData _getTemplateIcon(String? templateId) {
    switch (templateId) {
      case 'property':
        return Icons.home_work;
      case 'liability':
        return Icons.gavel;
      case 'cyber':
        return Icons.security;
      case 'marine':
        return Icons.directions_boat;
      case 'professional':
        return Icons.business_center;
      default:
        return Icons.description;
    }
  }

  String _formatDate(String? dateStr) {
    if (dateStr == null) return 'N/A';
    try {
      final date = DateTime.parse(dateStr);
      return '${date.day}/${date.month}/${date.year}';
    } catch (e) {
      return dateStr;
    }
  }
}
